export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const PROFILE_LIST = 'PROFILE_LIST';
export const GET_ALL_REPOS = 'GET_ALL_REPOS';

export const PROFILE_GITHUBREPOS = 'PROFILE_GITHUBREPOS';
